Citizen.CreateThread(function()
  local cInteriorId = GetInteriorAtCoords(5505.03, 5397.68, 590.0)
  ActivateInteriorEntitySet(cInteriorId, "set_arena_dirt")
  ActivateInteriorEntitySet(cInteriorId, "set_npa")
  RefreshInterior(cInteriorId)
end)

RegisterCommand("arena-off", function()
  local cInteriorId = GetInteriorAtCoords(5505.03, 5397.68, 590.0)
  DeactivateInteriorEntitySet(cInteriorId, "set_arena_dirt")
  DeactivateInteriorEntitySet(cInteriorId, "set_npa")
  RefreshInterior(cInteriorId)
end, false)

RegisterCommand("arena-dirt", function()
  local cInteriorId = GetInteriorAtCoords(5505.03, 5397.68, 590.0)
  ActivateInteriorEntitySet(cInteriorId, "set_arena_dirt")
  RefreshInterior(cInteriorId)
end, false)

RegisterCommand("arena-gokart", function()
  local cInteriorId = GetInteriorAtCoords(5505.03, 5397.68, 590.0)
  ActivateInteriorEntitySet(cInteriorId, "set_gokart")
  RefreshInterior(cInteriorId)
end, false)

RegisterCommand("arena-wasteland", function()
  local cInteriorId = GetInteriorAtCoords(5505.03, 5397.68, 590.0)
  ActivateInteriorEntitySet(cInteriorId, "set_npa")
  RefreshInterior(cInteriorId)
end, false)