CREATE TABLE `710_crypto` (
	`coin` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`value` INT(11) NULL DEFAULT NULL,
	`highestever` INT(11) NULL DEFAULT NULL,
	`lowestever` INT(11) NULL DEFAULT NULL,
	`weeklyhigh` INT(11) NULL DEFAULT NULL,
	`weeklylow` INT(11) NULL DEFAULT NULL,
	`weeklytime` DATETIME NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

ALTER TABLE `710_users`
	ADD COLUMN `crypto` LONGTEXT NULL DEFAULT NULL