----------------------------------
--<!>-- BOII | DEVELOPMENT --<!>--
----------------------------------

-- Language settings
Language = {
    Targeting = {
        ['dutyicon'] = 'fas fa-clipboard', -- Icon used by qb-target for on duty location visit; https://fontawesome.com to change
        ['dutylabel'] = 'Clock In/Out', -- Label used by qb-target for on duty location
        ['bossicon'] = 'fas fa-clipboard-list', -- Icon used by qb-target for boss menu location visit; https://fontawesome.com to change
        ['bosslabel'] = 'Job Management', -- Label used by qb-target for boss menu location
        ['bossstorageicon'] = 'fas fa-box', -- Icon used by qb-target for boss storage locations visit; https://fontawesome.com to change
        ['bossstoragelabel'] = 'Open Management Storage', -- Label used by qb-target for boss storage locations
        ['jobstorageicon'] = 'fas fa-box', -- Icon used by qb-target for job storage locations visit; https://fontawesome.com to change
        ['jobstoragelabel'] = 'Open Storage', -- Label used by qb-target for job storage locations
        ['eposicon'] = 'fas fa-cash-register', -- Icon used by qb-target for payment locations visit; https://fontawesome.com to change
        ['eposlabel'] = 'Charge Customer', -- Label used by qb-target for payment locations
        ['traystorageicon'] = 'fas fa-shopping-cart', -- Icon used by qb-target for tray storage locations visit; https://fontawesome.com to change
        ['traystoragelabel'] = 'Collect Order', -- Label used by qb-target for tray storage locations 
        ['rollingicon'] = 'fas fa-cannabis', -- Icon used by qb-target for rolling location visit; https://fontawesome.com to change
        ['rollinglabel'] = 'Roll Joints', -- Label used by qb-target for rolling location
        ['jobstoreicon'] = 'fas fa-shopping-basket', -- Icon used by qb-target for job store locations visit; https://fontawesome.com to change
        ['jobstorelabel'] = 'Purchase Stock', -- Label used by qb-target for job store locations
        ['snacktableicon'] = 'fas fa-shopping-basket', -- Icon used by qb-target for snack table locations visit; https://fontawesome.com to change
        ['snacktablelabel'] = 'Purchase Snacks', -- Label used by qb-target for snack table locations
        ['outfiticon'] = 'fas fa-shirt', -- Icon used by qb-target for wardrobe location visit; https://fontawesome.com to change
        ['outfitlabel'] = 'Change Outfit', -- Label used by qb-target for wardrobe location
        ['trimicon'] = 'fas fa-cut', -- Icon used by qb-target for trimming locations visit; https://fontawesome.com to change
        ['trimlabel'] = 'Trim Cannabis', -- Label used by qb-target for trimming locations
        ['harvesticon'] = 'fas fa-cannabis', -- Icon used by qb-target for harvesting locations visit; https://fontawesome.com to change
        ['strain1label'] = 'Harvest Skunk Plants', -- Label used by qb-target for harvesting strain 1 plant
        ['strain2label'] = 'Harvest Kush Plants', -- Label used by qb-target for harvesting strain 2 plants
        ['strain3label'] = 'Harvest White Widow Plants', -- Label used by qb-target for harvesting strain 3 plants
        ['strain4label'] = 'Harvest AK47 Plants', -- Label used by qb-target for harvesting strain 4 plants
        ['strain5label'] = 'Harvest Amnesia Plants', -- Label used by qb-target for harvesting strain 5 plants
        ['strain6label'] = 'Harvest Purple Haze Plants', -- Label used by qb-target for harvesting strain 6 plants
        ['strain7label'] = 'Harvest Gelato Plants', -- Label used by qb-target for harvesting strain 7 plants
        ['strain8label'] = 'Harvest Zkittles Plants', -- Label used by qb-target for harvesting strain 8 plants
        ['bongicon'] = 'fas fa-bong', -- Icon used by boii-target for bong table locations visit; https://fontawesome.com to change
        ['bonglabel'] = 'Take A Hit From The Bong', -- Label used by bong table locations
        ['ediblesicon'] = 'fas fa-cannabis', -- Icon used by qb-target for edibles location visit; https://fontawesome.com to change
        ['edibleslabel'] = 'Prepare Edibles', -- Label used by qb-target for edibles location
        ['garageicon'] = 'fas fa-car', -- Icon used by qb-target for garage location visit; https://fontawesome.com to change
        ['garagelabel'] = 'Company Vehicle', -- Label used by qb-target for garage location
        ['forceentryicon'] = 'fa-solid fa-unlock', -- Icon used by qb-target for force entry into storage locations visit; https://fontawesome.com to change
        ['forceentrylabel'] = 'Force Open Storage', -- Label used by qb-target for force entry into storage locations 
    },
    Locations = {
        Duty = {
            ['dutymenuheader'] = 'Staff Duty', -- Menu header
            ['dutymenuheadertext'] = 'Clock in and out of duty here!', -- Menu header text
            ['dutymenuheadericon'] = 'fa-solid fa-briefcase', -- Menu header icon
            ['dutytoggle'] = '• Clock In/Out', -- Menu header
            ['dutytoggleicon'] = 'fa-solid fa-clock', -- Menu header icon
        },
        Billing = {
            ['paymenuheader'] = 'White Widow', -- Menu header
            ['paymenuheadertext'] = 'Charge Customer', -- Menu header text
            ['invoicesent'] = 'Invoice sent successfully!', -- Notification
            ['invoicereceived'] = 'Invoice received!', -- Notification
            ['minamount'] = 'You cant charge someone nothing idiot..', -- Notification
            ['billself'] = 'You cant bill yourself idiot..', -- Notification
            ['billoffline'] = 'You cant bill someone whos not in city idiot..', -- Notification
            ['noaccess'] = 'You are not authorised to make sales..', -- Notification
            ['paytext'] = 'paypal id', -- Input text when charging customers
            ['payamount'] = '$ amount', -- Input text when charging customers
        },
        Rolling = {
            ['jointsmenuheader'] = 'Joint Rolling Station', -- Menu header
            ['jointsmenuheadertext'] = 'Rolling up your joints here!', -- Menu header text
            ['jointsmenuheadericon'] = 'fa-solid fa-joint', -- Menu header icon
            ['strain1menuheader'] = 'CBD Skunk', -- Menu header
            ['strain1menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain1.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain1.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain1.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain1.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain1.RequiredItems['2'].label..'', -- Menu header text
            ['strain1menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain2menuheader'] = 'CBD OG-Kush', -- Menu header
            ['strain2menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain2.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain2.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain2.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain2.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain2.RequiredItems['2'].label..'', -- Menu header text
            ['strain2menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain3menuheader'] = 'CBD White-Widow', -- Menu header
            ['strain3menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain3.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain3.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain3.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain3.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain3.RequiredItems['2'].label..'', -- Menu header text
            ['strain3menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain4menuheader'] = 'CBD AK-47', -- Menu header
            ['strain4menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain4.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain4.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain4.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain4.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain4.RequiredItems['2'].label..'', -- Menu header text
            ['strain4menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain5menuheader'] = 'CBD Amnesia', -- Menu header
            ['strain5menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain5.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain5.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain5.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain5.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain5.RequiredItems['2'].label..'', -- Menu header text
            ['strain5menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain6menuheader'] = 'CBD Purple-Haze', -- Menu header
            ['strain6menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain6.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain6.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain6.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain6.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain6.RequiredItems['2'].label..'', -- Menu header text
            ['strain6menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain7menuheader'] = 'CBD Gelato', -- Menu header
            ['strain7menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain7.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain7.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain7.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain7.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain7.RequiredItems['2'].label..'', -- Menu header text
            ['strain7menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain8menuheader'] = 'CBD Zkittles', -- Menu header
            ['strain8menuheadertext'] = 'Required:</p>'..Config.JobSettings.JointRolling.Strain8.RemoveAmount..'x '..Config.JobSettings.Trimming.Strain8.ReturnItem['1'].label..'</p>1x '..Config.JobSettings.JointRolling.Strain8.RequiredItems['1'].label..'</p>'..Config.JobSettings.JointRolling.Strain8.RequiredItems['2'].amount..'x '..Config.JobSettings.JointRolling.Strain8.RequiredItems['2'].label..'', -- Menu header text
            ['strain8menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
        },
        Trimming = {
            ['trimmenuheader'] = 'Trimming Station', -- Menu header
            ['trimmenuheadertext'] = 'Trim your crops into something usable!', -- Menu header text
            ['trimmenuheadericon'] = 'fa-solid fa-scissors', -- Menu header icon
            ['strain1menuheader'] = 'CBD Skunk', -- Menu header
            ['strain1menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain1.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain1.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain1.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain1.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain1.RequiredItems['3'].label..'', -- Menu header text
            ['strain1menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain2menuheader'] = 'CBD OG-Kush', -- Menu header
            ['strain2menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain2.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain2.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain2.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain2.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain2.RequiredItems['3'].label..'', -- Menu header text
            ['strain2menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain3menuheader'] = 'CBD White-Widow', -- Menu header
            ['strain3menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain3.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain3.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain3.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain3.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain3.RequiredItems['3'].label..'', -- Menu header text
            ['strain3menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain4menuheader'] = 'CBD AK-47', -- Menu header
            ['strain4menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain4.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain4.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain4.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain4.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain4.RequiredItems['3'].label..'', -- Menu header text
            ['strain4menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain5menuheader'] = 'CBD Amnesia', -- Menu header
            ['strain5menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain5.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain5.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain5.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain5.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain5.RequiredItems['3'].label..'', -- Menu header text
            ['strain5menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain6menuheader'] = 'CBD Purple-Haze', -- Menu header
            ['strain6menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain6.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain6.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain6.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain6.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain6.RequiredItems['3'].label..'', -- Menu header text
            ['strain6menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain7menuheader'] = 'CBD Gelato', -- Menu header
            ['strain7menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain7.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain7.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain7.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain7.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain7.RequiredItems['3'].label..'', -- Menu header text
            ['strain7menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['strain8menuheader'] = 'CBD Zkittles', -- Menu header
            ['strain8menuheadertext'] = 'Required: </p>1x '..Config.JobSettings.Trimming.Strain8.RequiredItems['1'].label..'</p>'..Config.JobSettings.Trimming.Strain8.RequiredItems['2'].amount..'x '..Config.JobSettings.Trimming.Strain8.RequiredItems['2'].label..'</p>'..Config.JobSettings.Trimming.Strain8.RequiredItems['3'].amount..'x '..Config.JobSettings.Trimming.Strain8.RequiredItems['3'].label..'', -- Menu header text
            ['strain8menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['noshears'] = 'You cant trim without shears fool..', -- Notification
            ['noweed'] = 'You need weed dumbass..', -- Notification
            ['enoughweed'] = 'You still dont have enough weed dumbass..', -- Notification
            ['enoughbags'] = 'You still dont have enough bags stupid..', -- Notification
            ['nobags'] = 'What are you planning to put the weed in? Get some bags..', -- Notification
            ['trimmingweed'] = 'Trimming Weed..', -- Progressbar
            ['trimmedweed'] = 'You successfully trimmed some weed!', -- Notification        
        },
        Harvest = {
            ['harvestedplant'] = 'You successfully harvested from a plant!', -- Notification
            ['strain1harvest'] = 'Harvesting Skunk..', -- Progressbar
            ['strain2harvest'] = 'Harvesting OG-Kush..', -- Progressbar
            ['strain3harvest'] = 'Harvesting White-Widow..', -- Progressbar
            ['strain4harvest'] = 'Harvesting AK47..', -- Progressbar
            ['strain5harvest'] = 'Harvesting Amnesia..', -- Progressbar
            ['strain6harvest'] = 'Harvesting Purple-Haze..', -- Progressbar
            ['strain7harvest'] = 'Harvesting Gelato..', -- Progressbar
            ['strain8harvest'] = 'Harvesting Zkittlez..', -- Progressbar
        },
        JointRolling = {
            ['enoughweed'] = 'You still dont have enough weed to roll up stupid..', -- Notification
            ['noweed'] = 'How are you planning to roll up without weed stupid..', -- Notification
            ['enoughpapers'] = 'You still dont have enough papers idiot..', -- Notification
            ['nopapers'] = 'You cant roll up without papers dumbass..', -- Notification
            ['nogrinder'] = 'You need a grinder to roll joints idiot..', -- Notification
            ['rolledjoints'] = 'You successfully rolled some joints!', -- Notification
            ['rollingjoints'] = 'Rolling Joints..', -- Progressbar
        },
        Edibles = {
            ['ediblesmenuheader'] = 'Cooking Table', -- Menu header
            ['ediblesmenuheadertext'] = 'Prepare edibles here!', -- Menu header text
            ['ediblesmenuheadericon'] = 'fa-solid fa-fire-burner', -- Menu header text
            ['strain1menuheader'] = 'CBD Skunk Gummies', -- Menu header 
            ['strain1menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain1.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain1.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain1.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain1.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain1.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain1.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain1.RequiredItems['3'].label..'', -- Menu header text
            ['strain1menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain2menuheader'] = 'CBD OG-Kush Gummies', -- Menu header 
            ['strain2menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain2.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain2.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain2.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain2.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain2.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain2.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain2.RequiredItems['3'].label..'', -- Menu header text
            ['strain2menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain3menuheader'] = 'CBD White-Widow Gummies', -- Menu header 
            ['strain3menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain3.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain3.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain3.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain3.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain3.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain3.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain3.RequiredItems['3'].label..'', -- Menu header text
            ['strain3menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain4menuheader'] = 'CBD AK-47 Gummies', -- Menu header 
            ['strain4menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain4.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain4.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain4.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain4.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain4.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain4.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain4.RequiredItems['3'].label..'', -- Menu header text
            ['strain4menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain5menuheader'] = 'CBD Amnesia Gummies', -- Menu header 
            ['strain5menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain5.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain5.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain5.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain5.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain5.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain5.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain5.RequiredItems['3'].label..'', -- Menu header text
            ['strain5menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain6menuheader'] = 'CBD Purple-Haze Gummies', -- Menu header 
            ['strain6menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain6.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain6.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain6.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain6.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain6.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain6.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain6.RequiredItems['3'].label..'', -- Menu header text
            ['strain6menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain7menuheader'] = 'CBD Gelato Gummies', -- Menu header 
            ['strain7menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain7.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain7.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain7.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain7.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain7.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain7.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain7.RequiredItems['3'].label..'', -- Menu header text
            ['strain7menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain8menuheader'] = 'CBD Zkittles Gummies', -- Menu header 
            ['strain8menuheadertext'] = 'Required:</p>'..Config.JobSettings.Edibles.Strain8.RequiredItems['1'].label..'</p>'..Config.JobSettings.Edibles.Strain8.RemoveAmount..'x '..Config.JobSettings.Harvest.Strain8.ReturnItem['1'].label..'</p>'..Config.JobSettings.Edibles.Strain8.RequiredItems['2'].amount..'x '..Config.JobSettings.Edibles.Strain8.RequiredItems['2'].label..'</p>'..Config.JobSettings.Edibles.Strain8.RequiredItems['3'].amount..'x '..Config.JobSettings.Edibles.Strain8.RequiredItems['3'].label..'', -- Menu header text
            ['strain8menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['enoughweed'] = 'You still dont have enough weed to prepare edibles stupid..', -- Notification
            ['noweed'] = 'How are you planning to roll up without weed stupid..', -- Notification
            ['noitem1'] = 'You cant prepare gummy bears without a mould!', -- Notification
            ['enoughitem2'] = 'You still dont have enough gelatine!', -- Notification
            ['noitem2'] = 'You dont have any gelatine!', -- Notification
            ['enoughitem3'] = 'You still dont have enough honey!', -- Notification
            ['noitem3'] = 'You dont have any honey!', -- Notification
            ['makeedibles'] = 'Preparing Edibles..', -- Progressbar
            ['eatedibles'] = 'Eating A Edible..', -- Progressbar
        },
        BongTables = {
            ['bongmenuheader'] = 'Hit The Bong', -- Menu header
            ['bongmenuheadertext'] = 'Required:</p>1x CBD Weed: 2g</p>Lighter', -- Menu header text
            ['bongmenuheadericon'] = 'fas fa-bong', -- Menu header text
            ['strain1menuheader'] = 'CBD Skunk', -- Menu header 
            ['strain1menuheadertext'] = 'Yo ass stunk like a skunk..', -- Menu header text
            ['strain1menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain2menuheader'] = 'CBD OG-Kush', -- Menu header 
            ['strain2menuheadertext'] = 'The K-U-S-H keeps us so high..', -- Menu header text 
            ['strain2menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain3menuheader'] = 'CBD White-Widow', -- Menu header 
            ['strain3menuheadertext'] = 'I bust put that white widow weed in the..', -- Menu header text 
            ['strain3menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain4menuheader'] = 'CBD AK-47', -- Menu header 
            ['strain4menuheadertext'] = 'AK47, MAC-11, Glocks, and 9s..', -- Menu header text 
            ['strain4menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain5menuheader'] = 'CBD Amnesia', -- Menu header 
            ['strain5menuheadertext'] = 'But my amnes way more potent..', -- Menu header text 
            ['strain5menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain6menuheader'] = 'CBD Purple-Haze', -- Menu header 
            ['strain6menuheadertext'] = 'Crack that dutch, roll that purple up..', -- Menu header text 
            ['strain6menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain7menuheader'] = 'CBD Gelato', -- Menu header 
            ['strain7menuheadertext'] = 'Its strictly top shelf, i aint burning bunk..', -- Menu header text 
            ['strain7menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon 
            ['strain8menuheader'] = 'CBD Zkittles', -- Menu header 
            ['strain8menuheadertext'] = 'Zkittles, man can taste the rainbow..', -- Menu header text 
            ['strain8menuheadericon'] = 'fa-solid fa-cannabis', -- Menu header icon
            ['noweed'] = 'How are you planning to smoke without weed stupid..', -- Notification
            ['usebong'] = 'Hitting The Bong..', -- Progressbar
        },
        Garage = {
            ['returnedvan'] = 'Thank you for returning the van!', -- Notification
            ['rentedvan'] = 'You took out a van! Return it when your done!', -- Notification
            ['nomoney'] = 'You cant afford the deposit dumbass..', -- Notification
            ['rentheader'] = 'White Widow Garage', -- Menu header
            ['rentheadericon'] = 'fa-solid fa-warehouse', -- Menu header
            ['rentmenuheader'] = 'Company Van', -- Menu header
            ['rentmenutext'] = 'A deposit of $'..Config.JobSettings.Garage.Deposit..' is required.', -- Menu text
            ['rentmenuicon'] = 'fa-solid fa-car', -- Menu icon
            ['returnmenuheader'] = 'Return Van', -- Menu header
            ['returnmenutext'] = 'Return Vehicle to receive $'..math.floor(Config.JobSettings.Garage.Deposit/2), -- Menu text
            ['returnmenuicon'] = 'fa-solid fa-car', -- Menu icon
        }
    },
    Joints = {
        ['smokejoint'] = 'Hitting The Blunt..', -- Progressbar
    },
    Shared = {
        ['returnmenu'] = 'Return', -- Menu header
        ['returnmenuicon'] = 'fa-solid fa-backward', -- Menu header icon
        ['exitmenu'] = 'Exit', -- Menu header
        ['exitmenuicon'] = 'fa-solid fa-circle-xmark', -- Menu header icon
        ['cancelled'] = 'Action cancelled..', -- Notification
        ['noinvent'] = 'Looks like your pockets are full..', -- Notification
        ['outrange'] = 'Looks like you are too far away..', -- Notification
        ['searchcd'] = 'You have already searched this location.. come back later..', -- Notification
        ['nolighter'] = 'How are you planning to smoke without a lighter stupid..', -- Notification 
        ['forceentry'] = 'Forcing Entry..', -- Progressbar
    }
}