local interiors = {

    {
        ipl = 'gabz_vbm_store_01_milo_', -- A1 Store Slot
        coords = { x = -1273.3335, y = -1410.4198, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = true },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_02_milo_', -- A2 Store Slot
        coords = { x = -1269.70081, y = -1415.61218, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = true },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_03_milo_', -- A3 Store Slot
        coords = { x = -1266.06616, y = -1420.8031, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = true },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_04_milo_', -- A4 Store Slot
        coords = { x = -1262.4314, y = -1425.994, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = true },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_05_milo_', -- B1 Store Slot
        coords = { x = -1255.162, y = -1436.37585, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = true },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_06_milo_', -- B2 Store Slot
        coords = { x = -1251.52722, y = -1441.56677, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = true },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_07_milo_', -- B3 Store Slot
        coords = { x = -1247.89258, y = -1446.75769, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = true },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_08_milo_', -- B4 Store Slot
        coords = { x = -1244.25, y = -1451.94, z = 4.836831 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = true },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_09_milo_', -- C1 Store Slot
        coords = { x = -1233.144, y = -1441.376, z = 4.836 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = true },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_10_milo_', -- C2 Store Slot
        coords = { x = -1227.952, y = -1437.744, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = true },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_11_milo_', -- C3 Store Slot
        coords = { x = -1222.7610, y = -1434.1090, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = true },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_12_milo_', -- C4 Store Slot
        coords = { x = -1217.5700, y = -1430.4740, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = true },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_13_milo_', -- D1 Store Slot
        coords = { x = -1198.04000000, y = -1458.82000000, z = 4.83682800 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = true },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_14_milo_', -- D2 Store Slot
        coords = { x = -1203.23300000, y = -1462.45300000, z = 4.83682800 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = true },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_15_milo_', -- D3 Store Slot
        coords = { x = -1208.42400000, y = -1466.08700000, z = 4.83682800 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = true },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_16_milo_', -- D4 Store Slot
        coords = { x = -1213.61500000, y = -1469.72200000, z = 4.83682800 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = true },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_17_milo_', -- E1 Store Slot
        coords = { x = -1226.98700000, y = -1476.61400000, z = 4.83683100 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = true },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_18_milo_', -- E2 Store Slot
        coords = { x = -1223.35200000, y = -1481.80500000, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = true },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_19_milo_', -- E3 Store Slot
        coords = { x = -1219.71700000, y = -1486.99600000, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = true },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_20_milo_', -- E4 Store Slot
        coords = { x = -1216.08200000, y = -1492.18700000, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = true },
        }
    },
    {
        ipl = 'gabz_vbm_store_21_milo_', -- F1 Store Slot
        coords = { x = -1209.60000000, y = -1501.44100000, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = true },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_22_milo_', -- F2 Store Slot
        coords = { x = -1205.96700000, y = -1506.63300000, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = true },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_23_milo_', -- F3 Store Slot
        coords = { x = -1202.33300000, y = -1511.82400000, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = true },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = false },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
    {
        ipl = 'gabz_vbm_store_24_milo_', -- F4 Store Slot
        coords = { x = -1198.69800000, y = -1517.01500000, z = 4.8368 },
        entitySets = {
            { name = 'store_empty', enable = false },
            { name = 'store_office', enable = true },
            { name = 'store_phone_a', enable = false },
            { name = 'store_phone_b', enable = false },
            { name = 'store_phone_c', enable = false },
            { name = 'store_liquor_a', enable = false },
            { name = 'store_liquor_b', enable = false },
            { name = 'store_liquor_c', enable = false },
            { name = 'store_bikes_a', enable = false },
            { name = 'store_bikes_b', enable = false },
            { name = 'store_bikes_c', enable = false },
            { name = 'store_masks_a', enable = false },
            { name = 'store_masks_b', enable = false },
            { name = 'store_masks_c', enable = true },
            { name = 'store_pharma_a', enable = false },
            { name = 'store_pharma_b', enable = false },
            { name = 'store_pharma_c', enable = false },
            { name = 'store_food_a', enable = false },
            { name = 'store_food_b', enable = false },
            { name = 'store_food_c', enable = false },
            { name = 'store_weed_a', enable = false },
            { name = 'store_weed_b', enable = false },
            { name = 'store_weed_c', enable = false },
            { name = 'store_cafe_a', enable = false },
            { name = 'store_cafe_b', enable = false },
            { name = 'store_cafe_c', enable = false },
        }
    },
}    
CreateThread(function()
    for _, interior in ipairs(interiors) do
        if not interior.ipl or not interior.coords or not interior.entitySets then
            print('Error while loading interior.')
            return
        end
        RequestIpl(interior.ipl)
        local interiorID = GetInteriorAtCoords(interior.coords.x, interior.coords.y, interior.coords.z)
        if IsValidInterior(interiorID) then
            for __, entitySet in ipairs(interior.entitySets) do
                if entitySet.enable then
                    EnableInteriorProp(interiorID, entitySet.name)
                    if entitySet.color then
                        SetInteriorPropColor(interiorID, entitySet.name, entitySet.color)
                    end
                else
                    DisableInteriorProp(interiorID, entitySet.name)
                end
            end
            RefreshInterior(interiorID)
        end
    end
    print("Interior data loaded.")
end)