Config = {}

-- PROPS ITEMS
Config.PropList = {
    ['stolentv'] = {
        ['name'] = 'A flatscreen',
        ['prop'] = 'prop_tv_flat_01',
        ['hash'] = `prop_tv_flat_01`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 10.00,
        },
    },
    ['stolenpc'] = {
        ['name'] = 'A computer',
        ['prop'] = 'prop_dyn_pc_02',
        ['hash'] = `prop_dyn_pc_02`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.22,
            ['XR'] = -80.00,
            ['YR'] = -15.00,
            ['ZR'] = -60.00,
        },
    },
    ['stolenmicro'] = {
        ['name'] = 'A microwave',
        ['prop'] = 'prop_micro_01',
        ['hash'] = `prop_micro_01`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.30,
            ['Y'] = 0.05,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 15.00,
        },
    },
    ['stolenart'] = {
        ['name'] = 'A art',
        ['prop'] = 'ex_mp_h_acc_artwalll_02',
        ['hash'] = `ex_mp_h_acc_artwalll_02`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 10.00,
        },
    },
    ['stolenlaptop'] = {
        ['name'] = 'A laptop',
        ['prop'] = 'prop_laptop_02_closed',
        ['hash'] = `prop_laptop_02_closed`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.30,
            ['Y'] = 0.05,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 15.00,
        },
    },
    ['stolencoffee'] = {
        ['name'] = 'A coffeemaker',
        ['prop'] = 'prop_coffee_mac_02',
        ['hash'] = `prop_coffee_mac_02`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.30,
            ['Y'] = 0.05,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 15.00,
        },
    },
    ['stolenscope'] = {
        ['name'] = 'A telescope',
        ['prop'] = 'prop_t_telescope_01b',
        ['hash'] = `prop_t_telescope_01b`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = -0.06,
            ['Y'] = 0.0,
            ['Z'] = -0.31,
            ['XR'] = 0.0,
            ['YR'] = 20.00,
            ['ZR'] = 0.0,
        },
    },
    ['stolensafe'] = {
        ['name'] = 'A Safevault',
        ['prop'] = 'prop_ld_int_safe_01',
        ['hash'] = `prop_ld_int_safe_01`,
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 10.00,
        },
    },
}